class Constants {
  static const String teacher = 'Teacher';
  static const String student = 'Student';
  static const String userType = 'userType';

  static List<String> cities =
  [
    "Abbottabad",
    "Adezai",
    "Ali Bandar",
    "Amir Chah",
    "Attock",
    "Ayubia",
    "Bahawalpur",
    "Baden",
    "Bagh",
    "Bahawalnagar",
    "Burewala",
    "Banda Daud Shah",
    "Bannu",
    "Batagram",
    "Bazdar",
    "Bela",
    "Bellpat",
    "Bhag",
    "Bhakkar",
    "Bhalwal",
    "Bhimber",
    "Birote",
    "Buner",
    "Burj",
    "Chiniot",
    "Chachro",
    "Chagai",
    "Chah Sandan",
    "Chailianwala",
    "Chakdara",
    "Chakku",
    "Chakwal",
    "Chaman",
    "Charsadda",
    "Chhatr",
    "Chichawatni",
    "Chitral",
    "Dadu",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Dalbandin",
    "Dargai",
    "Darya Khan",
    "Daska",
    "Dera Bugti",
    "Dhana Sar",
    "Digri",
    "Dina City|Dina",
    "Dinga",
    "Diwana",
    "Dokri",
    "Drosh",
    "Duki",
    "Dushi",
    "Duzab",
    "Faisalabad",
    "Fateh Jang",
    "Ghotki",
    "Gwadar",
    "Gujranwala",
    "Gujrat",
    "Gadra",
    "Gajar",
    "Gandava",
    "Garhi Khairo",
    "Garruck",
    "Ghakhar Mandi",
    "Ghanian",
    "Ghauspur",
    "Ghazluna",
    "Girdan",
    "Gulistan",
    "Gwash",
    "Hyderabad",
    "Hala",
    "Haripur",
    "Hab Chauki",
    "Hafizabad",
    "Hameedabad",
    "Hangu",
    "Harnai",
    "Hasilpur",
    "Haveli Lakha",
    "Hinglaj",
    "Hoshab",
    "Islamabad",
    "Islamkot",
    "Ispikan",
    "Jacobabad",
    "Jamshoro",
    "Jhang",
    "Jhelum",
    "Jamesabad",
    "Jampur",
    "Janghar",
    "Jati(Mughalbhin)",
    "Jauharabad",
    "Jhal",
    "Jhal Jhao",
    "Jhatpat",
    "Jhudo",
    "Jiwani",
    "Jungshahi",
    "Karachi",
    "Kotri",
    "Kalam",
    "Kalandi",
    "Kalat",
    "Kamalia",
    "Kamararod",
    "Kamber",
    "Kamokey",
    "Kanak",
    "Kandi",
    "Kandiaro",
    "Kanpur",
    "Kapip",
    "Kappar",
    "Karak City",
    "Karodi",
    "Kashmor",
    "Kasur",
    "Katuri",
    "Keti Bandar",
    "Khairpur",
    "Khanaspur",
    "Khanewal",
    "Kharan",
    "kharian",
    "Khokhropur",
    "Khora",
    "Khushab",
    "Khuzdar",
    "Kikki",
    "Klupro",
    "Kohan",
    "Kohat",
    "Kohistan",
    "Kohlu",
    "Korak",
    "Korangi",
    "Kot Sarae",
    "Kotli",
    "Lahore",
    "Larkana",
    "Lahri",
    "Lakki Marwat",
    "Lasbela",
    "Latamber",
    "Layyah",
    "Leiah",
    "Liari",
    "Lodhran",
    "Loralai",
    "Lower Dir",
    "Shadan Lund",
    "Multan",
    "Mandi Bahauddin",
    "Mansehra",
    "Mian Chanu",
    "Mirpur",
    "Mardan",
    "Mach",
    "Madyan",
    "Malakand",
    "Mand",
    "Manguchar",
    "Mashki Chah",
    "Maslti",
    "Mastuj",
    "Mastung",
    "Mathi",
    "Matiari",
    "Mehar",
    "Mekhtar",
    "Merui",
    "Mianwali",
    "Mianez",
    "Mirpur Batoro",
    "Mirpur Khas",
    "Mirpur Sakro",
    "Mithi",
    "Mongora",
    "Murgha Kibzai",
    "Muridke",
    "Musa Khel Bazar",
    "Muzaffar Garh",
    "Muzaffarabad",
    "Nawabshah",
    "Nazimabad",
    "Nowshera",
    "Nagar Parkar",
    "Nagha Kalat",
    "Nal",
    "Naokot",
    "Nasirabad",
    "Nauroz Kalat",
    "Naushara",
    "Nur Gamma",
    "Nushki",
    "Nuttal",
    "Okara",
    "Ormara",
    "Peshawar",
    "Panjgur",
    "Pasni City",
    "Paharpur",
    "Palantuk",
    "Pendoo",
    "Piharak",
    "Pirmahal",
    "Pishin",
    "Plandri",
    "Pokran",
    "Pounch",
    "Quetta",
    "Qambar",
    "Qamruddin Karez",
    "Qazi Ahmad",
    "Qila Abdullah",
    "Qila Ladgasht",
    "Qila Safed",
    "Qila Saifullah",
    "Rawalpindi",
    "Rabwah",
    "Rahim Yar Khan",
    "Rajan Pur",
    "Rakhni",
    "Ranipur",
    "Ratodero",
    "Rawalakot",
    "Renala Khurd",
    "Robat Thana",
    "Rodkhan",
    "Rohri",
    "Sialkot",
    "Sadiqabad",
    "Safdar Abad- (Dhaban Singh)",
    "Sahiwal",
    "Saidu Sharif",
    "Saindak",
    "Sakrand",
    "Sanjawi",
    "Sargodha",
    "Saruna",
    "Shabaz Kalat",
    "Shadadkhot",
    "Shahbandar",
    "Shahpur",
    "Shahpur Chakar",
    "Shakargarh",
    "Shangla",
    "Sharam Jogizai",
    "Sheikhupura",
    "Shikarpur",
    "Shingar",
    "Shorap",
    "Sibi",
    "Sohawa",
    "Sonmiani",
    "Sooianwala",
    "Spezand",
    "Spintangi",
    "Sui",
    "Sujawal",
    "Sukkur",
    "Suntsar",
    "Surab",
    "Swabi",
    "Swat",
    "Tando Adam",
    "Tando Bago",
    "Tangi",
    "Tank City",
    "Tar Ahamd Rind",
    "Thalo",
    "Thatta",
    "Toba Tek Singh",
    "Tordher",
    "Tujal",
    "Tump",
    "Turbat",
    "Umarao",
    "Umarkot",
    "Upper Dir",
    "Uthal",
    "Vehari",
    "Veirwaro",
    "Vitakri",
    "Wadh",
    "Wah Cantt",
    "Warah",
    "Washap",
    "Wasjuk",
    "Wazirabad",
    "Yakmach",
    "Zhob"
  ];

  static List<String> classes = [
    'Preschool',
    'Class 1 to 5',
    'Class 6 to 8',
    'Matric',
    'Intermediate',
    'A Level',
    'O Level',
    'Bachelors',
    'Masters',
    'Test Prep',
    'Diploma/Certifications'
  ];

  static List<String> minQualification = [

    'Intermediate',
    'A Level',
    'O Level',
    'Bachelors',
    'Masters',
    'MPhil',
    'Phd'
  ];

  static List<String> subjects = [
    'Accounting and Auditing',
    'Agriculture',
    'Applied Mathematics',
    'Arabic',
    'Archaeology',
    'Architecture',
    'Auditing and Income Tax Law',
    'Banking',
    'Biochemistry',
    'Biology',
    'Botany',
    'Business Administration',
    'Business Communication',
    'Business Law',
    'Business Mathematics',
    'Business Taxation',
    'Chemistry',
    'Civics',
    'Commerce',
    'Communication Studies',
    'Computer Assisted Instructions',
    'Computer Science',
    'Current Affairs',
    'Curriculum and Instructions',
    'Economics',
    'Education',
    'Educational Psychology & Guidance',
    'Education Sociology',
    'Engineering and Technology',
    'English',
    'English Literature',
    'Essay',
    'Ethics',
    'Fine Arts',
    'Food and Nutrition',
    'Forestry',
    'Fundamental Marketing',
    'General Science',
    'Geography',
    'Geology',
    'Graphic Arts and Designing',
    'Health Education',
    'History',
    'Home Economics',
    'International Relations',
    'Introduction to Business',
    'Islamiat',
    'Islamiat Elective',
    'Journalism',
    'Law',
    'Library Science',
    'Logic',
    'Management',
    'Marketing',
    'Mass Communication',
    'Mathematics',
    'Measurement and Evaluation in Education',
    'Nursing',
    'Pak Studies',
    'Pakistan Affairs',
    'Pharmacy',
    'Philosophy',
    'Physics',
    'Physiology',
    'Political Science',
    'Principles of Accounting',
    'Principles of Commerce',
    'Principles of Economics',
    'Principles of Insurance',
    'Principles of Trade',
    'Psychology',
    'Public Administration',
    'Public Health',
    'Pure Mathematics',
    'School Organization and Management',
    'Social Science',
    'Social Work',
    'Sociology',
    'Space Sciences',
    'Statistics',
    'Veterinary Sciences'
  ];


  static List<String> skills = [
    'Freelancing',
    'Amazon',
    'Beautician Training',
    'Calligraphy',
    'Confidence Building',
    'Cooking',
    'Exam Pressure Management',
    'Exercise and Fitness',
    'IELTS',
    'Judo Karate and Self Defense',
    'Kids Behavior Improvement',
    'Memorization Techniques',
    'Music',
    'Painting',
    'Quran Reading',
    'Spoken English',
    'Swimming',
    'Typing',
    'Weight Loss',
    'Yoga'
  ];

  static const colCity = 'city';
  static const colSubject = 'subject';
  static const colClass = 'class';
  static const colSkill = 'skill';


}











